# Generated by Django 3.1.1 on 2020-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('place', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('star_cast', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('vote', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
